@HiveServer_HostAddress = http://localhost:5242


POST {{HiveServer_HostAddress}}/CreateAccount
Content-Type: application/json

{
    "Email" : "kaon7723@tukroea.ac.kr",
    "Password":"a1234567890"
}

###

POST {{HiveServer_HostAddress}}/Login
Content-Type: application/json

{
    "Email" : "kaon7723@tukroea.ac.kr",
    "Password":"a1234567890"
}
###
POST {{HiveServer_HostAddress}}/VerifyToken
Content-Type: application/json

{
    "Email" : "kaon7723@tukroea.ac.kr",
    "Token":"a1234567890"
}
###